apiVersion: apps/v1
kind: Deployment

metadata:
  name: kavyagpt-frontend
  namespace: kavyagpt

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: kavya1111999/kavyagpt-frontend:v1

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "500m"