apiVersion: apps/v1
kind: Deployment

metadata:
  name: kavyagpt-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      containers:
        - name: frontend

          image: kavya1111999/kavyagpt-frontend:v1

          imagePullPolicy: Always

          ports:
            - containerPort: 80